In [1]:
import pandas as pd
import os

In [2]:
final_unit_conversion_table = pd.read_csv("../../dependencies/final_unit_conversion_table.csv")

In [18]:

new_row1 = pd.DataFrame([{"Incoming Unit": "°fahrenheit", "ceed_unit": "°C", "formula": "((x) - 32)*(5/9)"}])  
new_row2 = pd.DataFrame([{"Incoming Unit": "°celsius", "ceed_unit": "°C", "formula": "x"}]) 
final_unit_conversion_table = pd.concat([final_unit_conversion_table, new_row1, new_row2], ignore_index=True)

In [19]:
final_unit_conversion_table[final_unit_conversion_table['ceed_unit'].isin(["°C"])]

          Incoming Unit ceed_unit           formula
3                    ºf        °C  ((x) - 32)*(5/9)
45                   °f        °C  ((x) - 32)*(5/9)
1370                 °c        °C                 x
1480                 °k        °C        x - 273.15
1481           degree k        °C        x - 273.15
1482              deg k        °C        x - 273.15
1483              deg f        °C  ((x) - 32)*(5/9)
1484           degree f        °C  ((x) - 32)*(5/9)
1485              deg c        °C                 x
1486           degree c        °C                 x
1487            °kelvin        °C        x - 273.15
1488      degree kelvin        °C        x - 273.15
1489         deg kelvin        °C        x - 273.15
1490     deg fahrenheit        °C  ((x) - 32)*(5/9)
1491  degree fahrenheit        °C  ((x) - 32)*(5/9)
1492        deg celsius        °C                 x
1493     degree celsius        °C                 x
1494        °fahrenheit        °C  ((x) - 32)*(5/9)
1495           °celsius        °C                 x

In [11]:
final_unit_conversion_table

     Incoming Unit ceed_unit           formula
0              gpa       MPa          (x)*1000
1            in/in         %           (x)*100
2              psi       MPa    (x)*0.00689476
3               ºf        °C  ((x) - 32)*(5/9)
4            g/cm3     kg/m³          (x)*1000
...            ...       ...               ...
1475         ohm-m     Ohm*m                 x
1476         ohm.m     Ohm*m                 x
1477         ohm m     Ohm*m                 x
1478          ohmm     Ohm*m                 x
1479         kg/m3     kg/m³                 x

[1480 rows x 3 columns]

In [20]:
final_unit_conversion_table.to_csv("../../dependencies/final_unit_conversion_table.csv",index=False)