In [1]:
import os
os.environ['HTTPS_PROXY']='czgdcsdwankerb1.czds.bz:8080'
#!pip install snowflake-connector-python
#!pip install pymssql
#!pip install "snowflake-connector-python[pandas]"
#!pip install sqlalchemy==1.4.46

In [5]:
!pip install snowflake-snowpark-python -U

Requirement already satisfied: snowflake-connector-python in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (3.1.1)
Requirement already satisfied: platformdirs<3.9.0,>=2.6.0 in d:\users\dscrs3\appdata\roaming\python\python310\site-packages (from snowflake-connector-python) (3.5.1)
Requirement already satisfied: filelock<4,>=3.5 in d:\users\dscrs3\appdata\roaming\python\python310\site-packages (from snowflake-connector-python) (3.12.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (2023.5.7)
Requirement already satisfied: oscrypto<2.0.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (1.3.0)
Requirement already satisfied: pyOpenSSL<24.0.0,>=16.2.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (23.2.0)
Requirement already satisfied: typing-extensions<5,>=4.3 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (4.6.3)
Requirement already satisfied: pycryptodomex!=3.5.0,<4.0.0,>=3.2 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (3.18.0)
Requirement already satisfied: packaging in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (23.1)
Requirement already satisfied: cffi<2.0.0,>=1.9 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (1.15.1)
Requirement already satisfied: idna<4,>=2.5 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (3.1.0)
Requirement already satisfied: tomlkit in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (0.12.1)
Requirement already satisfied: pyjwt<3.0.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (2.8.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: requests<3.0.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (2.31.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (1.26.16)
Requirement already satisfied: pytz in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (2023.3)
Requirement already satisfied: cryptography<42.0.0,>=3.1.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (41.0.3)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: pycparser in d:\users\dscrs3\.conda\envs\prodigy\lib\site-packages (from cffi<2.0.0,>=1.9->snowflake-connector-python) (2.21)

In [1]:
from snowflake.snowpark import Session

ModuleNotFoundError: No module named 'snowflake'

In [3]:
#!pip install snowflake

Collecting snowflake
  Downloading snowflake-0.0.4.tar.gz (2.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: snowflake
  Building wheel for snowflake (setup.py): started
  Building wheel for snowflake (setup.py): finished with status 'done'
  Created wheel for snowflake: filename=snowflake-0.0.4-py3-none-any.whl size=3263 sha256=96e3309ffbf9ba0754be29bf3c719c0d63f75df60cc9a2def05e9b19b0c9c970
  Stored in directory: d:\users\dscrs3\appdata\local\pip\cache\wheels\e5\76\9d\769b7a5eca0432a4610f88fd9c6ddad9bf0ab05494baa81578
Successfully built snowflake
Installing collected packages: snowflake
Successfully installed snowflake-0.0.4

In [13]:
# conn = create_engine('mssql+pymssql://sqldbadmin:rYxz&5m~VjQrr&tm@mssql-gst-dev-ussc-01.database.windows.net/mssqldb-gst-dev-ussc-01')
# df = pd.read_sql_query('select * from SFTRaw.Nsf',con=con)

In [3]:
import json
connection_parameters = json.load(open('snowflake_creds.json'))

import snowflake.connector
conn = snowflake.connector.connect(
    user=connection_parameters["user"],
    authenticator=connection_parameters["authenticator"],
    account=connection_parameters["account"],
    warehouse=connection_parameters["warehouse"],
    database=connection_parameters["database"],
    schema=connection_parameters["schema"],
    role=connection_parameters["role"],
    protocol='https'
    )

ModuleNotFoundError: No module named 'snowflake'

In [2]:
cur = conn.cursor()

In [4]:
cur.execute("""select PRODUCT_LINE,POLYMER,PRODUCT_CD,PROPERTY_NAME, NON_STD_TEST_COND_DESC,VALUE_ASSMNT_SI,UNIT_OF_MEAS_SI, TEMP_C2 
from GST_Curated.SPT""")
SPT = cur.fetch_pandas_all()
SPT.to_csv("./Data/SPT.csv",index=False)

In [6]:
PROPERTY = SPT[SPT['TEMP_C2']!='GST specific info']
PROPERTY.reset_index(drop=True,inplace=True)
PROPERTY.to_csv("./Data/PROPERTY.csv",index=False)

In [7]:
FILLER = SPT[SPT['TEMP_C2']=='GST specific info']
FILLER.reset_index(drop=True,inplace=True)
FILLER = FILLER.rename({"PROPERTY_NAME":"Filler Type","VALUE_ASSMNT_SI":"Filler %"},axis=1)
FILLER.to_csv("./Data/FILLER.csv",index=False)

In [8]:
cur.execute("""select PRODUCT_CD, VALUE_ASSMNT_SI as FEATURE from GST_Curated.FEATURE
WHERE PROPERTY_NAME NOT IN ('Approval','Delivery Form','Regulatory')""")
FEATURE = cur.fetch_pandas_all()
FEATURE.to_csv("./Data/FEATURE.csv",index=False)

In [9]:
cur.execute("""select PRODUCT_NAME, INDUSTRY_GROUP, MARKET, MARKET_SEGMENT, SUB_SEGMENT, APPLICATION 
from GST_Curated.APPLICATION_MAP_SFDC
""")
APPLICATION = cur.fetch_pandas_all()
APPLICATION.to_csv("./Data/APPLICATION.csv",index=False)

In [10]:
cur.execute("""select * from GST_Curated.COMPETITOR_DATA""")
COMPETITOR_DATA = cur.fetch_pandas_all()
COMPETITOR_DATA.to_csv("./Data/COMPETITOR_DATA.csv",index=False)

In [11]:
cur.execute("""select * from GST_Curated.CTQ""")
CTQ = cur.fetch_pandas_all()
CTQ.to_csv("./Data/CTQ.csv",index=False)

In [12]:
cur.execute("""select * from GST_Curated.TDS_MAPPING""")
TDS_MAPPING = cur.fetch_pandas_all()
TDS_MAPPING.to_csv("./Data/TDS_MAPPING.csv",index=False)

In [3]:
cur.execute("""select * 
from GST_Curated.RAILWAY""")
RAILWAY = cur.fetch_pandas_all()
RAILWAY.shape

(1094, 17)

In [6]:
cur.execute("""select * 
from GST_Curated.WATER_APPROVALS""")
WATER_APPROVALS = cur.fetch_pandas_all()
WATER_APPROVALS.shape

(300, 15)

In [5]:
cur.execute("""select * 
from GST_Curated.NSF""")
NSF = cur.fetch_pandas_all()
NSF.shape

(499, 5)

In [6]:
cur.close()

True

In [17]:
SPT["POLYMER"].unique()

array(['PA66', 'PA6', 'PE-UHMW', 'PE-HMW', 'PP', 'TPV', 'POM', 'PPS',
       'LCP', 'PPA', 'PA*', 'PA666', 'PE-HD', 'TPU', 'PCT'], dtype=object)

In [22]:
SPT['PRODUCT_LINE'].unique()

array(['CELANYL®', 'GUR®', 'CELSTRAN®', 'SANTOPRENE®', 'CELCON®',
       'HOSTAFORM®', 'FRIANYL®', 'FORTRON®', 'VECTRA®', 'ECOMID®',
       'KEPITAL®', 'ZENITE®', 'COOLPOLY®', 'HOSTAFORM', 'THERMX®'],
      dtype=object)

In [35]:
FEATURE['FEATURE'].unique()

array(['Bio-based', 'Flame retardant', 'Injection molding',
       'Glass reinforced', 'High flow', 'Heat resistant',
       'Wear resistant', 'Unfilled', 'Impact modified', 'Low emission',
       'Specialty', 'Sustainable', 'Profile extrusion', 'Low warpage',
       'Auto spec approved', 'Light stabilized', 'Blow molding',
       'Lead-free soldering', 'Compression molding', 'Tribological',
       'UV resistant', 'Specialty appearance', 'Platable',
       'Electrostatic dissipation', 'Extrusion', 'Mineral reinforced',
       'Chemical resistant', 'Mineral/Glass reinforced',
       'Transfer molding', 'Thermoforming', 'Multi injection molding',
       'Injection blow molding', 'Lighting', 'High crystallinity',
       'High gloss', 'Film extrusion', 'Recycled content',
       'Other extrusion', 'Laser direct structuring (LDS)',
       'Extrusion blow molding', 'Sheet extrusion', 'Vacuum forming',
       'Aramid reinforced', 'Medical/Healthcare', 'Fuel resistant',
       'Carbon fiber reinforced', 'Improved creep', 'Anti-static',
       'High viscosity', 'Color concentrate', 'Thermally conductive',
       'Laser markable', 'Coextrusion', 'Electrically conductive',
       'Low odor', 'Gel spinning (fibers)', 'Light weighting',
       'Improved weld line', 'Reduced gloss', 'Calandering',
       'Selective reinforcement', 'Porous sintering',
       'Concentrate blend down', 'Polymer blend', 'Chlorine resistant',
       'Hydrolysis resistant', 'Stainless steel reinforced',
       'Foam extrusion', 'Rotomolding', 'Coating'], dtype=object)

In [39]:
PROPERTY['PROPERTY_NAME'].unique()

array(['DTUL at 0.45 MPa', 'Density', 'Charpy notched impact strength',
       'Flexural modulus', 'Elongational Stress F', 'Flexural stress',
       'Tensile modulus', 'Intrinsic viscosity',
       'Tensile strain at break', 'Flammability @0.8mm nom. thickn.',
       'Flammability @3.2mm nom. thickn.', 'FMVSS', 'DTUL at 8.0 MPa',
       'Compression set, 70°C, 22h, Type 1, Method B', 'Water absorption',
       'Izod impact notched', 'Tensile stress at break', 'Melt flow rate',
       'Fiber Content', 'Tensile strain at yield', 'DTUL at 1.8 MPa',
       'Melting temperature', 'Surface resistivity, 23°C',
       'Tensile stress at 100%, perpendicular',
       'Hot wire ignition @ 1.6mm nom. thickn.',
       'Average molecular weight', 'Charpy impact strength',
       'Tear strength, Die C, perpendicular', 'Melt volume rate',
       'Flammability @1.6mm nom. thickn.', 'High amp arc ignition (HAI)',
       'Viscosity number (PA)', 'Tensile stress at yield',
       'Coeff. of linear therm expansion', 'Comparative tracking index',
       'Ball indentation hardness', 'Continuous service temperature',
       'RTI Elec', 'Humidity absorption', 'Vicat softening temperature',
       'Tensile creep modulus', 'Flame rating, 1.5 mm',
       'Compression set, 125°C, 70h, Type A',
       'Flexural Strain at Failure', 'RTI - str @ 1.6mm nom. Thickn.',
       'Tensile stress at 50% strain', 'Izod impact unnotched',
       'Flexural strength', 'Tensile nominal strain at break',
       'Detergent resistance', 'Poissons ratio',
       'Flammability at thickness h', 'Dielectric constant (Dk)',
       'Compression set, 70°C, 22h, Type A',
       'Dielectric Constant 60Hz, 1.98 mm',
       'Flexural stress at max. force', 'Tensile Modulus - Tape',
       'Compression set, 23°C, 22h, Type 1, Method B',
       'Average particle size', 'RTI Str, 3.0 mm', 'Flame rating, 1.0 mm',
       'Electric strength, 23°C (AC)',
       'Compression set, 125°C, 70h, Type 1, Method B',
       'Tape Areal Weight', 'Rockwell hardness (M-Scale)',
       'Low temperature brittleness', 'Fiber Areal Weight',
       'Glow wire flammability index',
       'Wear by sandslurry method (based on GUR 4120=100)',
       'Viscosity number (PE and PP)', 'Glow wire ignition temperature',
       'Tensile strength at break elast, perpendicular',
       'RTI Str, 1.5 mm', 'Volume resistivity, 23°C',
       'Dissipation factor', 'Flame rating, 3.0 mm', 'RTI Str, 1.0 mm',
       'Compression set, 100°C, 168h, Type A',
       'Tensile strain at break, perpendicular', 'Shore D hardness-TPE',
       'Hot-wire Ignition (1.5 mm)', 'Flexural stress at 3.5% strain',
       'Tensile stress at break, perpendicular', 'Burning rate',
       'Shore A hardness-TPE', 'RTI - str @ 0.8mm nom. Thickn.',
       'High ampere arc ignition @ 3.2mm nom. thickn.',
       'Flexural Strength - Tape', 'Molding shrinkage (average)',
       'Tensile Strength', 'Thermal diffusivity',
       'Elongation at break elast, perpendicular',
       'High voltage arc tracking rate (HVTR)',
       'Compressive stress at 1% strain', 'CLTE above Tg',
       'Compressive stress at 6% strain', 'Brittleness temperature',
       'Compression set, 23°C, 22h, Type A', 'Bulk density',
       'Thermal conductivity', 'Dielectric Strength, 2.0 mm',
       'Outdoor suitability', 'EMI shielding effectiveness, 1GHz',
       'Flame rating, 1.1 mm', 'Flammability @0.4mm nom. thickn.',
       'Electric strength at high temperature (AC)',
       'Tensile strain at yield, perpendicular',
       'High voltage arc resistance to ignition (HVAR)', 'Odor test',
       'Ball pressure test', 'Tear strength, Method Ba, perpendicular',
       'Specific heat', 'RTI - electrical @ 1.6mm nom. Thickn.',
       'RTI Str', 'Emission of organic compounds',
       'Apparent viscosity at 200 1/s',
       'Compression set, 23°C, 168h, Type A',
       'Hot-wire Ignition (1.0 mm)', 'Glass transition temperature',
       'Flexural Modulus - Tape', 'RTI - electrical @ 0.4mm nom. Thickn.',
       'Volume resistivity, 2.0 mm',
       'Hot wire ignition @ 0.8mm nom. thickn.',
       'RTI - electrical @ 0.8mm nom. Thickn.',
       'Electric strength at high temperature (DC)',
       'RTI - impact @ 3.2mm nom. Thickn.',
       'Compression set, 23°C, 168h, Type 1, Method B',
       'Hot wire ignition (1.6 mm)', 'Arc resistance',
       'RTI - impact @ 0.8mm nom. Thickn.',
       'Compression set, 100°C, 168h, Type 1, Method B',
       'Hot-wire Ignition (3.0 mm)',
       'High ampere arc ignition @ 0.8mm nom. thickn.',
       'Charpy double 14°v-notch strength',
       'Hot wire ignition @ 3.2mm nom. thickn.', 'Compressive modulus',
       'Flexural stress at break', 'Flexural strain at flexural strength',
       'Surface resistivity at high temperature',
       'Thermal desorption analysis of organic emissions',
       'Flexural strain at break', 'CLTE below Tg',
       'Apparent viscosity at 1200 1/s', 'Tape Thickness',
       'Volume resistivity at high temperature',
       'Compression set, 23°C, 70h, Type 1, Method B',
       'Tensile stress at yield, perpendicular', 'Tape Width',
       'Molding shrinkage', 'Limiting oxygen index (LOI)',
       'Tensile Strain at Failure', 'Fiber Volume', 'Hot wire ignition',
       'RTI - str @ 3.2mm nom. Thickn.', 'RTI Str, 1.1 mm',
       'Dielectric Constant, 60Hz, 2.03 mm', 'Tensile set (elastomers)',
       'RTI - electrical @ 3.2mm nom. Thickn.',
       'Comparative tracking index CTI M',
       'Dielectric Constant, 60Hz, 1.93 mm', 'Flame rating, 0.75 mm',
       'Rockwell hardness (R-Scale)', 'Specific heat capacity',
       'Electric strength, 23°C (DC)',
       'High ampere arc ignition @ 1.6mm nom. thickn.',
       'RTI - impact @ 1.6mm nom. Thickn.',
       'Compression set, 100°C, 22h, Type 1, Method B',
       'Shore A hardness-TPE (on extruded tape (x3))',
       'Tensile strength at yield, perpendicular',
       'Compression set, 100°C, 70h, Type A', 'CSA rating @ 0.84 mm',
       'Tensile elongation at yield, perpendicular',
       'RTI - str @ 0.4mm nom. Thickn.',
       'Compression set, 70°C, 168h, Type A', 'Specific Resistivity',
       'Flame rating, 1.6 mm', 'RTI - impact @ 0.4mm nom. Thickn.',
       'RTI Str, 1.6 mm', 'Volume resistivity, 3.2 mm',
       'Hot wire ignition (1.8 mm)',
       'Compression set, 100°C, 70h, Type 1, Method B',
       'Shore A hardness', 'Dielectric Constant, 60Hz, 1.96 mm',
       'Dielectric Constant 60Hz, 1.96 mm',
       'Dielectric Constant 60Hz, 1.93 mm',
       'High ampere arc ignition @ 0.4mm nom. thickn.',
       'Inclined-plane tracking, 2.5 kV',
       'Flammability 5V at thickness h', 'Static decay',
       'Compression set, 100°C, 22h, Type A', 'Puncture energy',
       'Compression set, 100°C, 300h, Type A',
       'Hot wire ignition @ 0.4mm nom. thickn.', 'Flame rating, 1.7 mm',
       'Flame rating, 2.9 mm', 'Flame rating, 1.8 mm',
       'Dielectric Constant 60Hz, 2.03 mm',
       'Compression set, 70°C, 168h, Type 1, Method B',
       'Dielectric Constant, 60Hz, 2.01 mm',
       'Compression set, 100°C, 300h, Type 1, Method B',
       'Compression set, 23°C, 70h, Type A',
       'Dielectric Constant 60Hz, 2.01 mm'], dtype=object)

In [37]:
FILLER['Filler Type'].unique()

array(['Carbon fiber load', 'Total load', 'Glass fiber (short) load',
       'Glass fiber (long) load', 'Glass bead load',
       'Mineral filler load', 'Conductive filler load',
       'PTFE filler load', 'Specialty filler load',
       'Glass fiber (continuous) load', 'Aramid fiber load',
       'Stainless steel fiber load', 'Graphite filler load'], dtype=object)

In [33]:
APPLICATION.head()

,PRODUCT_NAME,INDUSTRY_GROUP,MARKET,MARKET_SEGMENT,SUB_SEGMENT,APPLICATION
0,CS PP-GF50-0405 P10/10 FS,Automotive & Transportation,Exterior,Door Components,Lock Systems,Automotive tank-lever
1,VE S471D-3 VD3137 BLACK D1,Consumer Goods,Appliance,Small Appliance,Microwave Ovens,NaN
2,STPDEVELOPMENTAL A8 (PS),Automotive & Transportation,Exterior,Exterior Trim,"WS dense dynamic, semi dynamic extruded e.g. d...",Glass Run Channel (GRC) for Automotive Exterior
3,CS +PP-GF30-04CN02/10 FS,Automotive & Transportation,Exterior,Door Components,Window Lift Kinematics,Cable drum-housing
4,CN M90 CF2001 NATURAL A1,Industrial,Fluid (Media) Handling,"Other (Plumbing, Hardware, Etc.)",NaN,O ring seal

In [11]:
COMPETITOR_DATA.head()

,PRODUCT_LINE,CELANESE_GRADE_NAME,CELANESE_POLYMER_TYPE,COMPETITOR,COMPETITOR_GRADE,COMPETITOR_POLYMER_TYPE
0,PA,Celanyl A3 H J20 NC 1102/T,PA66,Dupont,DUPONT ST801A NC-10,PA66
1,PA,Ecomid A HH M40 BK 9005/1,PA66,Dupont,MINLON 10B40-HSI BK-61,PA66
2,PA,Celanyl B3 HH M40 BK 9005/1,PA6,Dupont,MINLON 10B40-HSI BK-61,PA66
3,PA,Celanyl A3 W J4 M40 NC 1102/1,PA66,Dupont,MINLON 11C40 NC010,PA66
4,PA,Celanyl A3 BK 9005/1,PA66,Dupont,ZYTEL 101L BKB009,PA66

## Certification

In [13]:
import ast
import pymssql
import datetime
import itertools
import numpy as np
import pandas as pd
import sqlalchemy as sa
from datetime import date
from datetime import datetime as dt
from sqlalchemy import create_engine
from dateutil.parser import parse

In [102]:
def transform(cert):
    x = []
    if cert == 'wras 23':
        x = ['wras 23C']
    elif cert == 'wras 60':
        x = ['wras 60C']
    elif cert == 'wras 85':
        x = ['wras 85C']         
    elif cert == 'nsf61 23C':
        x = ['nsf61 23C', 'nsf61 73F']
    elif cert == 'nsf61 82C':
        x = ['nsf61 82C', 'nsf61 179.6F']       
    elif cert == 'acs 23':
        x = ['acs 23C', 'acs 73F']        
    elif cert == 'acs 60':
        x = ['acs 60C', 'acs 140F']       
    elif cert == 'acs 85':
        x = ['acs 85C', 'acs 185F']        
    elif cert == 'ktw bwgl en16421 P2 23C':
        x = ['ktw bwgl at 23C']       
    elif cert == 'ktw bwgl en16421 P2 60C':
        x = ['ktw bwgl at 60C']        
    elif cert == 'ktw bwgl en16421 P2 85C':
        x = ['ktw bwgl at 85C']
    elif cert == 'ktw bwgl en16421 P2 en16422':
        x = ['en16421']
    else:
        x = []
    return x

def is_date(string, fuzzy=False):
    try:
        parse(string, fuzzy=fuzzy)
        return True
    except ValueError:
        return False

#function to extract year and month from datetime date
def extract_year_month(df):
    cols=['wras_23c','wras_60c','wras_85c','ktw_bwgl_23c','ktw_bwgl_60c','ktw_bwgl_85c','en16421','acs_23c','acs_60c','acs_85c','Today_date']
    for i in cols:
        i=str(i)
        df[i+'_year']=pd.to_datetime(df[i]).dt.strftime('%Y')
        df[i+'_month']=pd.to_datetime(df[i]).dt.strftime('%m')
    return df

char1 = [
    'XXXXXX', 
    '..Other none', 
    '..Other', 'none', 
    '\n\t\t', 
    'as per SPAL Automotive', 
    '/ 1. Page material data', 
    'listed', 
    '"', "'", 
    'table 2', 
    'Only - not officially approved but best fit from Celanese portfolio to spec requirements',
    '(application specific)',
    'Color approved',
    '(limited approval)',
    'Limited approval for ',
    '(grey coloured masterbatch)',
    '(blue coloured masterbatch)',
    '100% COLOR MATCH',
    '100% Color Match',
    '(pre-compounded or Salt; Pepper)',
    '(Nanjing)',
    'Validated for Strut sensor by HGT',
    'Exterior',
    'Interior',
    'China',
    'as ',
    '*',
    'Specified on each application ',
    '(Campo Bom)',
    '(COLORS)',
    '(Kalahari)',
]

char2 = [
    '&amp',
    'no spec',
    '\xa0',
    '\t\t\t\t\t\t\t\t\t\t\t',
    '\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t',
    '<br />\t',
    '\t\t\t',
    '\t\t',
    '</th>',
    '<br />\n',
    '<br /><a href=https://iq.ul.com/ul/cert.aspx?ULID=102512443>',
    '</a>',
    '\n \n\n<tr>',
    ' \t<th>',
    '<th>',
    '<tr>',
    '- attached email/',
    'FTM Material Data Sheet PSA - attached',
    'No code - APTIV MSPEC document',
    'E ;E',
    'E  ;E',
    '(pre-compounded or Salt; Pepper)'
]

char3 = ["  ", "   ", "    ", "     ", "      ", " ,"]


def remove_1(string):
    for i in char1:
        string = string.replace(i, "")
    return string

def remove_2(string):
    for i in char2:
        string = string.replace(i, " ")
    return string

def remove_3(string):
    for i in char3:
        string = string.replace(i, "")
    return string

In [122]:
def azureml_main(dataframe1 = None):   
    con = create_engine('mssql+pymssql://sqldbadmin:rYxz&5m~VjQrr&tm@mssql-gst-dev-ussc-01.database.windows.net/mssqldb-gst-dev-ussc-01')

    dataframe1 = []

## ----------------------------------------------------------------------------------------------

    df = pd.read_sql_query('select * from SFTRaw.Nsf',con=con)
    df.columns = df.columns.str.lower()
    #df = df[df.doc_type == "ARF"]
    df['cert'] = np.where(df['standard'] == '042', 'nsf 42', '')
    df = df[df['cert'] == 'nsf 42']
    df['cert'] = df[['cert']].values.tolist()
    df['grade'] = df['primary_trade_name']
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

    # ingest and convert  nsf51 data
    df = pd.read_sql_query('select * from SFTRaw.Nsf',con=con)
    df.columns = df.columns.str.lower()
    #df = df[df.doc_type == "ARF"]
    df['cert'] = np.where(df['standard'] == '051', 'nsf 51', '')
    df = df[df['cert'] == 'nsf 51']
    df['cert'] = df[['cert']].values.tolist()
    df['grade'] = df['primary_trade_name']
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

    # ingest and convert  nsf61 data
    df = pd.read_sql_query('select * from SFTRaw.Nsf',con=con)
    df.columns = df.columns.str.lower()
    #df = df[df.doc_type == "ARF"]
    df['cert'] = np.where(df['standard'] == '061', 'nsf 61', '')
    df = df[df['cert'] == 'nsf 61']
    df['cert'] = df[['cert']].values.tolist()
    df['grade'] = df['primary_trade_name']
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

# ingest and convert  nsf61 23C and NSF61 82C
    df = pd.read_sql_query('select * from SFTRaw.Nsf',con=con)
    df.columns = df.columns.str.lower()
    print(df.columns)
    df = df[['primary_trade_name', 'nsf61_23c', 'nsf61_82c']]
    df = df.astype(str)
    # Transform nsf61
    df['nsf61_23c'] = np.where(df['nsf61_23c'] == 'Yes', 'nsf61 23c', '')
    df['nsf61_82c'] = np.where(df['nsf61_82c'] == 'Yes', 'nsf61 82c', '')
    #Transform
    df['nsf61_23c'] = df['nsf61_23c'].apply(lambda x: transform(x))
    df['nsf61_82c'] = df['nsf61_82c'].apply(lambda x: transform(x))
    df['cert'] = df['nsf61_82c'] + df['nsf61_23c']
    df['cert'] = df['cert'].apply(lambda x: list(filter(None, x)))
    df['grade'] = df['primary_trade_name']
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

    # ingest and convert railway data
    df = pd.read_sql_query('select * from SFTRaw.Railway',con=con)
    df.columns = df.columns.str.lower()
    df['grade'] = df['material_name']
    df['cert'] = df['railway_certification']
    ## df['c1'] = df['norm'] + " " + df['specification'] + " " + df['classification']
    ## df['c2'] = df['norm'] + " " + df['specification']
    ## df['c3'] = df['specification'] + " " + df['classification']
    df['cert']= df[['cert']].values.tolist()
    df['cert'] = df['cert'].apply(lambda x: list(filter(None, x)))	
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

    df = pd.read_sql_query('select * from SFTRaw.WaterApprovals',con=con)
    df.columns = df.columns.str.lower()
    print(df.columns)
    cols = df.columns[4:13]
    df[cols] = df[cols].apply(pd.to_datetime, errors='coerce')
    cols = list(df.select_dtypes(include=['datetime64']))
    df[cols] = df[cols].apply(lambda x: pd.to_datetime(x).dt.strftime('%m/%Y'))
    df[cols] = df[cols].apply(pd.to_datetime, errors='coerce')
    df = df.rename(columns={'ktw_bwgl_en16421_p2_23c': 'ktw_bwgl_23c', 'ktw_bwgl_en16421_p2_60c':'ktw_bwgl_60c', 'ktw_bwgl_en16421_p2_85c':'ktw_bwgl_85c', 'ktw_bwgl_en16421_p2_en16422':'en16421'})
    
        
    #getting Today's date
    Today=str(date.today())
    df['Today_date']=Today
    df['Today_date']=pd.to_datetime(df['Today_date'],errors='coerce')
    #Calling function for year and month extraction
    df=extract_year_month(df)
        
    #Filter 'wras' based on current year and month
    df['wras_23c']=np.where(((df['wras_23c_year']>df['Today_date_year'])|((df['wras_23c_month']>=df['Today_date_month'])&(df['wras_23c_year']==df['Today_date_year']))),df['wras_23c'].apply(str),"NaN")
    df['wras_60c']=np.where(((df['wras_60c_year']>df['Today_date_year'])|((df['wras_60c_month']>=df['Today_date_month'])&(df['wras_60c_year']==df['Today_date_year']))),df['wras_60c'].apply(str),"NaN")
    df['wras_85c']=np.where(((df['wras_85c_year']>df['Today_date_year'])|((df['wras_85c_month']>=df['Today_date_month'])&(df['wras_85c_year']==df['Today_date_year']))),df['wras_85c'].apply(str),"NaN")
    
     #Filter 'ktw' based on current year and month
    df['ktw_bwgl_23c']=np.where(((df['ktw_bwgl_23c_year']>df['Today_date_year'])|((df['ktw_bwgl_23c_month']>=df['Today_date_month'])&(df['ktw_bwgl_23c_year']==df['Today_date_year']))),df['ktw_bwgl_23c'].apply(str),"NaN")
    df['ktw_bwgl_60c']=np.where(((df['ktw_bwgl_60c_year']>df['Today_date_year'])|((df['ktw_bwgl_60c_month']>=df['Today_date_month'])&(df['ktw_bwgl_60c_year']==df['Today_date_year']))),df['ktw_bwgl_60c'].apply(str),"NaN")
    df['ktw_bwgl_85c']=np.where(((df['ktw_bwgl_85c_year']>df['Today_date_year'])|((df['ktw_bwgl_85c_month']>=df['Today_date_month'])&(df['ktw_bwgl_85c_year']==df['Today_date_year']))),df['ktw_bwgl_85c'].apply(str),"NaN")
    df['en16421']=np.where(((df['en16421_year']>df['Today_date_year'])|((df['en16421_month']>=df['Today_date_month'])&(df['en16421_year']==df['Today_date_year']))),df['en16421'].apply(str),"NaN")
    
    #Filter 'acs' based on current year and month
    df['acs_23c']=np.where(((df['acs_23c_year']>df['Today_date_year'])|((df['acs_23c_month']>=df['Today_date_month'])&(df['acs_23c_year']==df['Today_date_year']))),df['acs_23c'].apply(str),"NaN")
    df['acs_60c']=np.where(((df['acs_60c_year']>df['Today_date_year'])|((df['acs_60c_month']>=df['Today_date_month'])&(df['acs_60c_year']==df['Today_date_year']))),df['acs_60c'].apply(str),"NaN")
    df['acs_85c']=np.where(((df['acs_85c_year']>df['Today_date_year'])|((df['acs_85c_month']>=df['Today_date_month'])&(df['acs_85c_year']==df['Today_date_year']))),df['acs_85c'].apply(str),"NaN")

    df = df[[
    'grade',
    # 'nsf61_23c',
    # 'nsf61_82c',
    'wras_23c',
    'wras_60c',
    'wras_85c',
    'ktw_bwgl_23c',
    'ktw_bwgl_60c',
    'ktw_bwgl_85c',
    'en16421',
    'acs_23c',
    'acs_60c',
    'acs_85c']]

    col = df.columns[1:11]
    df[col] = df[col].apply(pd.to_datetime, errors='coerce')
    col = list(df.select_dtypes(include=['datetime64']))
    df[col] = df[col].apply(lambda x: pd.to_datetime(x).dt.strftime('%m/%Y'))
    df = df.astype(str)
        
    # # Transform nsf61
    # df['nsf61_23c'] = np.where(df['nsf61_23c'] == 'Yes', 'nsf61 23C', '')
    # df['nsf61_82c'] = np.where(df['nsf61_82c'] == 'Yes', 'nsf61 82C', '')

    # Transform wras
    df['wras_23c'] = df['wras_23c'].apply(lambda x: is_date(x))
    df['wras_60c'] = df['wras_60c'].apply(lambda x: is_date(x))
    df['wras_85c'] = df['wras_85c'].apply(lambda x: is_date(x))

    df['wras_23c'] = np.where(df['wras_23c'] == True, 'wras 23', "")
    df['wras_60c'] = np.where(df['wras_60c'] == True, 'wras 60', "")
    df['wras_85c'] = np.where(df['wras_85c'] == True, 'wras 85', "")


    # Transform acs
    df['acs_23c'] = df['acs_23c'].apply(lambda x: is_date(x))
    df['acs_60c'] = df['acs_60c'].apply(lambda x: is_date(x))
    df['acs_85c'] = df['acs_85c'].apply(lambda x: is_date(x))

    df['acs_23c'] = np.where(df['acs_23c'] == True, 'acs 23', "")
    df['acs_60c'] = np.where(df['acs_60c'] == True, 'acs 60', "")
    df['acs_85c'] = np.where(df['acs_85c'] == True, 'acs 85', "")


    # Transform ktw
    df['ktw_bwgl_23c'] = df['ktw_bwgl_23c'].apply(lambda x: is_date(x))
    df['ktw_bwgl_60c'] = df['ktw_bwgl_60c'].apply(lambda x: is_date(x))
    df['ktw_bwgl_85c'] = df['ktw_bwgl_85c'].apply(lambda x: is_date(x))
    df['en16421'] = df['en16421'].apply(lambda x: is_date(x))

    df['ktw_bwgl_23c'] = np.where(df['ktw_bwgl_23c'] == True, 'ktw bwgl en16421 P2 23C', "")
    df['ktw_bwgl_60c'] = np.where(df['ktw_bwgl_60c'] == True, 'ktw bwgl en16421 P2 60C', "")
    df['ktw_bwgl_85c'] = np.where(df['ktw_bwgl_85c'] == True, 'ktw bwgl en16421 P2 85C', "")
    df['en16421'] = np.where(df['en16421'] == True, 'ktw bwgl en16421 P2 en16422', "")

    # Transform
    # df['nsf61_23c'] = df['nsf61_23c'].apply(lambda x: transform(x))
    # df['nsf61_82c'] = df['nsf61_82c'].apply(lambda x: transform(x))
    df['wras_23c'] = df['wras_23c'].apply(lambda x: transform(x))
    df['wras_60c'] = df['wras_60c'].apply(lambda x: transform(x))
    df['wras_85c'] = df['wras_85c'].apply(lambda x: transform(x))
    df['acs_23c'] = df['acs_23c'].apply(lambda x: transform(x))
    df['acs_60c'] = df['acs_60c'].apply(lambda x: transform(x))
    df['acs_85c'] = df['acs_85c'].apply(lambda x: transform(x))
    df['ktw_bwgl_23c'] = df['ktw_bwgl_23c'].apply(lambda x: transform(x))
    df['ktw_bwgl_60c'] = df['ktw_bwgl_60c'].apply(lambda x: transform(x))
    df['ktw_bwgl_85c'] = df['ktw_bwgl_85c'].apply(lambda x: transform(x))
    df['en16421'] = df['en16421'].apply(lambda x: transform(x))

    # Create df['cert']
    df['cert'] = df['wras_23c'] + df['wras_60c'] + df['wras_85c'] + df['acs_23c'] + df['acs_60c'] + df['acs_85c'] + df['ktw_bwgl_23c'] + df['ktw_bwgl_60c'] + df['ktw_bwgl_85c'] + df['en16421']
    df['cert'] = df['cert'].apply(lambda x: list(filter(None, x)))
    dataframe1.append(df[['grade','cert']])

## ----------------------------------------------------------------------------------------------

    df = pd.read_sql_query("select * from SFTRaw.Feature where property_name='Approval'",con=con)

    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: remove_1(x))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: remove_2(x))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: remove_3(x))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.replace('(pre-compounded or Salt; Pepper)', ""))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.replace(' 100% Color match', ""))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.replace('COLOR MATCH', ""))
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.rstrip())
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.strip())
    df['VALUE_ASSMNT_SI'] = df['VALUE_ASSMNT_SI'].apply(lambda x: x.replace('Â', ""))

    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.replace('Â', ""))
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.replace('\xa0', ""))
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.replace('Chyrsler', 'Chrysler'))
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.replace('Diamler', 'Daimler'))
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.rstrip())
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.strip())
    df['TEMP_C2'] = df['TEMP_C2'].apply(lambda x: x.replace('Stellantis PSA', 'Stellantis - PSA'))
    df['TEMP_C2']=np.where(((df['TEMP_C2']=='Mercedes-Benz Group')|(df['TEMP_C2']=='Mercedes-Benz Group (Daimler')|(df['TEMP_C2']=='Mercedes-Benz Group (Diamler)')),'Mercedes-Benz Group (Daimler)',df['TEMP_C2'])

    #Create grade & cert columns
    df['grade'] = df['PRODUCT_CD']
    df['cert'] = df[['TEMP_C2', 'VALUE_ASSMNT_SI']].values.tolist()
    df['cert'] = df['cert'].apply(lambda x: list(filter(None, x)))
    dataframe1.append(df[['grade','cert']])

    dff = pd.concat(dataframe1)

    x = dff.groupby('grade')

    a1, b1 = [], []
    for i in x:
        g = i[0]
        aa = i[1]['cert'].values
        #print(aa)
        if aa.any() != None:
            #print(aa)
            val = set(itertools.chain.from_iterable(aa))
            print(val)
            a1.append(g)
            b1.append(val)
        else:
            a1.append(g)
            b1.append(None)
            
    df_cert = pd.DataFrame({'grade':a1, 'certifications':b1})
    df_cert['certifications'] = df_cert['certifications'].apply(list)
    df_cert = df_cert.astype(str)
    dataframe1 = df_cert

    dataframe1.to_sql('df_cert_remapped_pipeline', con=con, schema='SftTransform', index=False, if_exists='replace')
    

    return dataframe1

In [123]:
# con = create_engine('mssql+pymssql://sqldbadmin:rYxz&5m~VjQrr&tm@mssql-gst-dev-ussc-01.database.windows.net/mssqldb-gst-dev-ussc-01')

In [124]:
CERTIFICATION = azureml_main()

Index(['primary_trade_name', 'standard', 'facility_at', 'nsf61_23c',
       'nsf61_82c'],
      dtype='object')
Index(['product_line', 'grade', 'colour', 'preferred',
       'ktw_bwgl_en16421_p2_23c', 'ktw_bwgl_en16421_p2_60c',
       'ktw_bwgl_en16421_p2_85c', 'ktw_bwgl_en16421_p2_en16422', 'wras_23c',
       'wras_60c', 'wras_85c', 'acs_23c', 'acs_60c', 'acs_85c', 'comment'],
      dtype='object')
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 51', 'nsf 61'}
{'nsf 61'}
{'nsf 51'}
{'R23 - HL2 (EN 45545-2)', 'R22 - HL1 (EN 45545-2)'}
{'R23 - HL2 (EN 45545-2)', 'R22 - HL1 (EN 45545-2)'}
{'FTM64 0057', 'Stellantis - PSA Group', 'Renault', 'UB15', '01378_15_02001'}
{'Mercedes-Benz Group (Daimler)'}
{'Stellantis â€“ Chrysler', 'CP5476'}
{'VW50133', 'VW Group*'}
{'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'GM', 'VW50127', 'VW Group*', 'VW50133', 'GMW3038P-PA66-GF35J'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW Group*', 'VW50127'}
{'SAIC Motor', 'DBL 5408', 'VW Group*', 'Mercedes-Benz Group (Daimler)', 'VW50133', 'SMTC 5 310 015'}
{'VW50134', 'VW Group*'}
{'Mercedes-Benz Group (Daimler)', 'DBL 5409'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'UB15', 'Renault'}
{'VW50134', 'VW Group*'}
{'VW50134', 'VW Group*'}
{'VW50125', 'VW Group*', 'Renault', 'UB15'}
{'GMW3029P-PA6-GF30H', 'GM', 'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'Mercedes-Benz Group (Daimler)', 'DBL 5409'}
{'VW50125', 'VW50134', 'VW Group*'}
{'CP5341', 'TSM5516G-1', 'Toyota', 'Stellantis - Chrysler'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'Bosch', 'GMW17195P-POM-T1', 'GM', '28 B 22-X001'}
{'GS 93017', 'BMW'}
{'nsf 61'}
{'Ford', 'CP4165', 'Stellantis - Chrysler', 'WSB-M4D821-A'}
{'Ford', 'WSB-M4D883-A1'}
{'TST 055 54.10', 'CP1906', 'Stellantis - Chrysler', '28 B 22-X009', 'Bosch', 'CP2500', 'Continental', 'nsf 61'}
{'Toyota', 'nsf 61', 'TSM5606G-1'}
{'nsf 61'}
{'Toyota'}
{'Nissan', 'Honda'}
{'nsf 61'}
{'CP3761', 'Stellantis - Chrysler', 'TSM10-519', 'Toyota', 'nsf 61'}
{'nsf 61'}
{'Continental', 'nsf 61', 'TST 055 54.07'}
{'CP4570', 'CP4597', 'Stellantis - Chrysler'}
{'Ford', 'WSK-M4D635-A1', 'CP4155', 'Stellantis - Chrysler', 'Toyota', 'TSM5515G-1A', 'nsf 61'}
{'Ford', 'WSK-M4D635-A1', 'Li Auto', 'GM', 'Stellantis - Chrysler', 'Q/LiA5310020', 'TSM5515G-1A', 'POM-IC1-1', 'Nissan', 'TST 055 54.07', 'CP1986', 'CP4240', 'Toyota', 'GMW22P-POM-C1', 'Continental', 'nsf 61'}
{'nsf 61'}
{'POM-IC3-1', 'CP2794', 'Ford', 'Li Auto', 'Q/LiA5310020', 'Stellantis - Chrysler', 'WSK-M4D635-A3', 'GM', 'TSM5515G-1B', 'Nissan', 'Toyota', 'GMW22P-POM-C4', 'CP2436', 'Continental', 'TST 055 54.12', 'nsf 61'}
{'nsf 61'}
{'nsf 61'}
{'Hyundai', 'TST 055 54.07', 'Toyota', 'UB03f', 'EGW.PL.0603-POM-CO', 'IP13g', 'BJEV', 'Evergrande Auto', 'SMTC 5 310 020', 'GM', 'Stellantis - Chrysler', 'SAIC Motor', 'EP03a', 'MS237-09, Type A', '30.5251-0367.7', 'EP03-3', 'CP1586', 'Q-BJEV 01.59', 'TM-1005-50', 'CP3766', '28 B 22-O034', 'UB15', 'Tesla', 'TM-1005-40', 'Nissan', 'nsf 61', 'Geely', 'Ford', 'POM-IC2-1', 'Li Auto', 'Q/LiA5310020', 'WSK-M4D635-A2', 'TSM5515G-1B', 'Bosch', 'Renault', 'Great Wall Motor', 'Q/JLY J7110235B', 'GMW22P-POM-C2', 'GMP.POM.005', 'Continental', 'CP1532', 'MP05-01'}
{'nsf 61'}
{'nsf 61'}
{'TSM5515G-1BL', 'Honda', 'TSM5515G-1W', 'Toyota', 'Nissan'}
{'Toyota', 'TSM5515G-1BVL'}
{'TSM5709G-1', 'CP4931', 'Toyota', 'Stellantis - Chrysler'}
{'nsf 61'}
{'Continental', 'TST 055 54.23'}
{'CP4096', 'CP4097', 'nsf 61', 'Stellantis - Chrysler'}
{'nsf 61'}
{'nsf 61'}
{'Stellantis - Chrysler', 'CP2726', 'CP2940', 'TST 055 54.19', 'Continental'}
{'Ford', 'WSK-M4D840-A5', 'GM', 'Honda', 'Stellantis - Chrysler', 'CP4109', 'Toyota', 'GM 7831P-POM-042', 'Nissan'}
{'Ford', 'GM', 'Stellantis - Chrysler', 'GMW22P-POM-C1U', 'CP3111', 'WSB-M4D840-A4'}
{'GMW22P-POM-C4U', 'Ford', 'WSK-M4D840-A3', 'GM', 'Honda', 'Stellantis - Chrysler', 'CP3905', 'Nissan'}
{'Ford', 'TM-1005-40CU1', 'Changan', 'Honda', 'Stellantis - Chrysler', 'Li Auto', 'Q/LiA5310020', 'WSS-M4D840-A6', 'GM', 'WSK-M4D840-A1', 'CP1758', 'WSS-M4D840-B1', 'Tesla', 'CP4624', 'GMW22P-POM-C2U', 'MTS-F01-02-001-A3', 'Nissan', 'CP3110'}
{'TSM5515G-1', 'GMW22P-POM-C2L', 'GM', 'Stellantis - Chrysler', 'Honda', 'Q/JLY J7110235B', 'CP3694', 'Toyota', 'Geely'}
{'Q/LiA5310050', 'Evergrande Auto', 'Li Auto', 'EGW.PL.1501-PP-LGF20'}
{'Q/LiA5310050', 'Evergrande Auto', 'Li Auto', 'EGW.PL.1502-PP-LGF30'}
{'Ford', 'WSB-M4D677-A'}
{'Ford', 'GM', 'GMW17810P-PA66-GF40', 'WSB-M4D678-A'}
{'Ford', 'WSB-M4D679-A'}
{'Ford', 'GM', 'GMW17810P-PA66-GF60', 'WSB-M4D680-A'}
{'Ford', 'Li Auto', 'BMW', 'Stellantis - Chrysler', 'GS 93016', 'Q/LiA5310050', 'WSS-M4D865-B', 'CP4731', 'WSS-M4D865-B57'}
{'Ford', 'Li Auto', 'Stellantis - Chrysler', 'WSS-M4D865-B5', 'Q/LiA5310050', 'TM-1001-12,22', 'CP5104', 'CP5109', 'Tesla', 'WSS-M4D865-B7'}
{'GM', 'GMW17697P-PP-GF20E'}
{'GM', 'TM-1001-102220, 202220', 'Stellantis - Chrysler', 'Q/JLY J7111001A', 'DBL 5404', 'Mercedes-Benz Group (Daimler)', 'GMW15890P-PP-GF20E', 'Tesla', 'CP5149', 'Geely'}
{'Li Auto', 'SAIC Motor', 'Q/LiA5310050', 'Great Wall Motor', 'SMTC 5 310 041', 'Mercedes-Benz Group (Daimler)', 'DBL 5404', 'MP01 LG-01'}
{'CP3778', 'Stellantis - Chrysler'}
{'CP3778', 'Bosch', 'Stellantis - Chrysler', '28 B 09-GF027'}
{'GM', 'GMW15890P-PP-GF30E'}
{'Q-BJEV 01.33', 'Li Auto', 'BMW', 'GM', 'GS 93016', 'Q/LiA5310050', 'VW Group', 'GMW15890P-PP-GF30', 'VW44045', 'BJEV'}
{'DBL 5404', 'Mercedes-Benz Group (Daimler)', 'GM', 'GMW15890P-PP-GF30E'}
{'Ford', 'DB21 CP4949', 'Li Auto', 'GM', 'SAIC Motor', 'Stellantis - Chrysler', 'BMW', 'WSS-M4D865-B8', 'Q/LiA5310050', 'GS 97014', 'SMTC 5 310 041', 'WSS-M4D865-B4', 'WSS-M4D865-B7', 'GMW15890P-PP-GF30E'}
{'Q/LiA5310050', 'Li Auto'}
{'GM', 'GMW16272P-PP-GF40'}
{'Ford', 'Stellantis - Chrysler', 'WSS-M4D865-B1', 'CP5307'}
{'Ford', 'Stellantis - Chrysler', '28 B 09-GF026', 'WSS-M4D865-B1', 'CP4451', 'Bosch', 'Great Wall Motor', 'DBL 5418', 'Mercedes-Benz Group (Daimler)', 'MP01 LG-03'}
{'Q/LiA5310050', 'Li Auto'}
{'Ford', 'GMW15890P-PP-GF40', 'Li Auto', 'GM', 'Q/LiA5310050', 'WSS-M4D865-B1', 'Great Wall Motor', 'Dongfeng Motor', 'SLCLBG2016018', 'MP01 LG-03'}
{'Q/LiA5310050', 'Li Auto'}
{'EP15a', 'Renault'}
{'Q-BJEV 01.33', 'Li Auto', 'SAIC Motor', 'Q/LiA5310050', 'SMTC 5 310 041', 'BJEV'}
{'Ford', 'Stellantis - Chrysler', 'Stellantis - PSA Group', 'CP5346', 'WSS-M4D865-B3', 'B62 0300'}
{'Q/LiA5310050', 'Mercedes-Benz Group (Daimler)', 'DBL 5416', 'Li Auto'}
{'Mercedes-Benz Group (Daimler)', 'DBL 5416', 'VW Group'}
{'Li Auto', 'GM', 'Q/LiA5310050', 'CP5157', '28 B 09-GF024', 'Bosch', 'Stellantis - FCA Group', 'GMW15890P-PP-GF50-Type 50', 'GMW16272P-PP-GF50'}
{'Li Auto', 'GM', 'SAIC Motor', 'Q/LiA5310050', 'SMTC 5 310 041', 'GMW16272P-PP-GF50'}
{'CP5347', 'EP14', 'Stellantis - Chrysler', 'Renault'}
{'DBL 5404', 'Mercedes-Benz Group (Daimler)'}
{'nsf 61'}
{'GMW17802P-PA6-T1', 'GM', 'B62 0300 61/221E/210M+/C2B', 'Stellantis - PSA Group'}
{'wras 60C', 'wras 85C', 'acs 73F', 'wras 23C', 'acs 23C'}
{'wras 60C', 'wras 85C', 'acs 73F', 'wras 23C', 'acs 23C'}
{'wras 60C', 'wras 23C', 'wras 85C'}
set()
{'wras 23C'}
{'wras 23C'}
{'wras 23C'}
set()
set()
set()
{'nsf 61'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'FTM64 0027', 'Stellantis - PSA Group'}
{'FTM64 0027', 'Stellantis - PSA Group'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'VW50133', 'VW Group*'}
{'VW50133', 'VW Group'}
{'Ford', 'WRS-M4D673-B2', 'VW Group*', 'VW50133', 'VW50127'}
{'VW50133', 'VW Group*', 'VW50127'}
{'DBL 5416', 'Mercedes-Benz Group (Daimler)', '01994_16_00325', 'Stellantis - PSA Group'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW50134', 'VW Group*'}
{'VW50125', 'VW Group*'}
{'Mercedes-Benz Group (Daimler)'}
{'nsf 61'}
{'DBL 5420', 'acs 140F', 'GS 93016', 'MS244-02', 'IP03a', 'GMW17521P-PPS-GF40E', 'acs 23C', 'acs 185F', 'GM', 'Stellantis - Chrysler', 'WSL-M4D807-A', 'PPS(B60)-IPL-1', 'acs 85C', '28 B 14-GF010', 'wras 23C', 'CP4241', 'acs 60C', 'Dongfeng Motor', 'CP3502', 'wras 85C', '01994_15_00075', 'BMW', 'acs 73F', 'SLCLBG2019011', '61/217M-219E/H115/H0412/13', 'Mercedes-Benz Group (Daimler)', 'nsf 61', 'Nissan', 'Ford', 'wras 60C', 'Stellantis - PSA Group', 'Bosch', 'Renault', 'Hyundai', 'GMW17521P-PPS-GF40'}
{'wras 60C', 'wras 23C', 'nsf 61', 'wras 85C'}
{'acs 185F', 'wras 60C', 'wras 85C', 'DBL 5420', 'acs 140F', 'acs 73F', 'acs 85C', 'wras 23C', 'Mercedes-Benz Group (Daimler)', 'acs 60C', 'nsf 61', 'acs 23C'}
{'wras 60C', 'wras 23C', 'nsf 61', 'wras 85C'}
{'Mercedes-Benz Group (Daimler)'}
{'wras 60C', 'wras 23C', 'wras 85C'}
{'wras 60C', 'wras 23C', 'wras 85C'}
{'GM', 'GMW17519P-PPS-GF45MD20', 'BMW', 'GS 93016'}
{'Continental', 'TST 055 58.01'}
{'Continental', 'TST 055 58.03'}
{'Ford', 'WSF-M4D803-A2', 'TST 055 58.01', 'DBL 5404', 'Mercedes-Benz Group (Daimler)', 'Continental', 'nsf 61'}
{'Continental', 'TST 055 58.12'}
{'acs 73F', 'acs 23C'}
{'acs 185F', 'acs 140F', 'acs 73F', 'acs 85C', 'acs 60C', 'acs 23C'}
{'VW Group*'}
{'Ford', 'WSS-M4D1063-A1'}
{'UB02b', 'nsf 51', 'Renault'}
{'Ford', 'WSS-M4D1063-A2'}
{'GM', 'GMW17769-PPS-I-Type 2'}
{'GMW17521P-PPS-GF40-Type 2', 'acs 140F', 'IP03a', 'acs 23C', 'acs 185F', 'GM', 'Stellantis - Chrysler', 'acs 85C', 'nsf 51', 'wras 23C', 'MS244-02, Type A-2', 'acs 60C', 'CP3502', 'wras 85C', 'VW Group', 'acs 73F', 'VW50137', 'nsf 61', 'wras 60C', 'Renault', 'Hyundai'}
{'nsf 61'}
{'MS244-02, Type A-2', 'Hyundai'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'UB22c', 'UB22d', 'Stellantis - PSA Group', 'R22 - HL3 (EN 45545-2)', 'UB22b', 'VW Group*', 'Renault', 'PMP E&E', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'UB22a'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'UB22c', 'UB22d', 'Stellantis - PSA Group', 'R22 - HL3 (EN 45545-2)', 'Renault', 'PMP E&E', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'UB22a', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'UB22b'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'UB22c', 'UB22d', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'Renault', 'UB22a', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'UB22b'}
{'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)'}
{'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)'}
{'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)'}
{'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)'}
{'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)'}
{'UB22c', 'UB22d', 'R22 - HL3 (EN 45545-2)', 'UB22b', 'VW Group*', 'Renault', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)', 'UB22a'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'VW50133  ', 'VW Group*', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'Stellantis - PSA Group', 'R22 - HL3 (EN 45545-2)', 'VW Group*', 'PMP E&E', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'VW50133', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}
{'R26 (0.8 mm) - V0 (EN 45545-2)', 'R26 (1.6 mm) - V0 (EN 45545-2)', 'R22 - HL3 (EN 45545-2)', 'R26 (3.2 mm) - V0 (EN 45545-2)', 'R23 - HL3 (EN 45545-2)', 'R24 - HL3 (EN 45545-2)'}

In [142]:
CERTIFICATION.to_csv("./Data/CERTIFICATION.csv",index=False)